/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author daisy
 */
public class AccountSettings extends javax.swing.JFrame {

    Toolkit tk = Toolkit.getDefaultToolkit();
    
    public String CurrentHashedPassword;

    /**
     * Creates new form AccountSettings
     */
    public AccountSettings() {
        initComponents();

        UsernameSection.setVisible(false);
        UsernameField.setVisible(false);
        UsernameConfirmButton.setVisible(false);
        UniqueUsernameErrorMessage.setVisible(false);
        LongUsernameErrorMessage.setVisible(false);
        InappropriateUsernameErrorMessage.setVisible(false);

        PasswordSection.setVisible(false);
        CurrentPasswordField.setVisible(false);
        NewPasswordField.setVisible(false);
        PasswordConfirmButton.setVisible(false);
        PasswordCharactersErrorMessage.setVisible(false);

        EmailSection.setVisible(false);
        EmailField.setVisible(false);
        EmailConfirmButton.setVisible(false);
        InvalidEmailErrorMessage.setVisible(false);
        UniqueEmailErrorMessage.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PasswordCharactersErrorMessage = new javax.swing.JLabel();
        UniqueEmailErrorMessage = new javax.swing.JLabel();
        InvalidEmailErrorMessage = new javax.swing.JLabel();
        InappropriateUsernameErrorMessage = new javax.swing.JLabel();
        LongUsernameErrorMessage = new javax.swing.JLabel();
        UniqueUsernameErrorMessage = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        EmailConfirmButton = new javax.swing.JButton();
        EmailSection = new javax.swing.JLabel();
        NewPasswordField = new javax.swing.JPasswordField();
        PasswordConfirmButton = new javax.swing.JButton();
        CurrentPasswordField = new javax.swing.JPasswordField();
        PasswordSection = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        UsernameButton = new javax.swing.JButton();
        PasswordButton = new javax.swing.JButton();
        EmailButton = new javax.swing.JButton();
        UsernameField = new javax.swing.JTextField();
        UsernameConfirmButton = new javax.swing.JButton();
        UsernameSection = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PasswordCharactersErrorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Password Characters Error Message.png"))); // NOI18N
        getContentPane().add(PasswordCharactersErrorMessage);
        PasswordCharactersErrorMessage.setBounds(720, 770, 500, 150);

        UniqueEmailErrorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/UniqueEmailErrorMessage.png"))); // NOI18N
        getContentPane().add(UniqueEmailErrorMessage);
        UniqueEmailErrorMessage.setBounds(720, 760, 510, 140);

        InvalidEmailErrorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Invalid Email Error.png"))); // NOI18N
        getContentPane().add(InvalidEmailErrorMessage);
        InvalidEmailErrorMessage.setBounds(730, 780, 390, 100);

        InappropriateUsernameErrorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Inappropriate Username Error Message.png"))); // NOI18N
        getContentPane().add(InappropriateUsernameErrorMessage);
        InappropriateUsernameErrorMessage.setBounds(720, 760, 430, 140);

        LongUsernameErrorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Long Username Error.png"))); // NOI18N
        getContentPane().add(LongUsernameErrorMessage);
        LongUsernameErrorMessage.setBounds(720, 790, 510, 90);

        UniqueUsernameErrorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Unique Username Error Message.png"))); // NOI18N
        getContentPane().add(UniqueUsernameErrorMessage);
        UniqueUsernameErrorMessage.setBounds(720, 680, 500, 300);

        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(EmailField);
        EmailField.setBounds(150, 550, 1640, 70);

        EmailConfirmButton.setBorderPainted(false);
        EmailConfirmButton.setContentAreaFilled(false);
        EmailConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EmailConfirmButton);
        EmailConfirmButton.setBounds(790, 890, 370, 170);

        EmailSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Change Email Section.jpg"))); // NOI18N
        getContentPane().add(EmailSection);
        EmailSection.setBounds(10, 420, 1910, 673);

        NewPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NewPasswordField);
        NewPasswordField.setBounds(151, 700, 1640, 60);

        PasswordConfirmButton.setBorderPainted(false);
        PasswordConfirmButton.setContentAreaFilled(false);
        PasswordConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordConfirmButton);
        PasswordConfirmButton.setBounds(779, 885, 380, 180);
        getContentPane().add(CurrentPasswordField);
        CurrentPasswordField.setBounds(150, 550, 1640, 70);

        PasswordSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Change Password Section.jpg"))); // NOI18N
        getContentPane().add(PasswordSection);
        PasswordSection.setBounds(10, 430, 1910, 650);

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(40, 60, 190, 70);

        UsernameButton.setBorderPainted(false);
        UsernameButton.setContentAreaFilled(false);
        UsernameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameButton);
        UsernameButton.setBounds(209, 245, 310, 140);

        PasswordButton.setBorderPainted(false);
        PasswordButton.setContentAreaFilled(false);
        PasswordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordButtonActionPerformed(evt);
            }
        });
        getContentPane().add(PasswordButton);
        PasswordButton.setBounds(809, 245, 300, 150);

        EmailButton.setBorderPainted(false);
        EmailButton.setContentAreaFilled(false);
        EmailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EmailButton);
        EmailButton.setBounds(1419, 255, 310, 140);
        getContentPane().add(UsernameField);
        UsernameField.setBounds(149, 552, 1640, 60);

        UsernameConfirmButton.setBorderPainted(false);
        UsernameConfirmButton.setContentAreaFilled(false);
        UsernameConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameConfirmButtonActionPerformed(evt);
            }
        });
        getContentPane().add(UsernameConfirmButton);
        UsernameConfirmButton.setBounds(789, 885, 370, 170);

        UsernameSection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Change Username Section.jpg"))); // NOI18N
        getContentPane().add(UsernameSection);
        UsernameSection.setBounds(10, 400, 1880, 700);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Change Account Details Base.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(1, 6, 1930, 1090);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        GUIs.NormalSettings normalSettings = new GUIs.NormalSettings();

        int WidthSize = (int) tk.getScreenSize().getWidth();
        int HeightSize = (int) tk.getScreenSize().getHeight();

        normalSettings.setSize(WidthSize, HeightSize);
        normalSettings.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void UsernameConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameConfirmButtonActionPerformed
        
        UniqueUsernameErrorMessage.setVisible(false);
        LongUsernameErrorMessage.setVisible(false);
        InappropriateUsernameErrorMessage.setVisible(false);
        
        String NewUsername = UsernameField.getText();
        boolean check = false;

        while (true) {
            if (NewUsername.length() > 25) {
                LongUsernameErrorMessage.setVisible(true);
                check = true;
                break;
            }
            
            String LoweredUsername= NewUsername.toLowerCase();
            System.out.println(LoweredUsername);
            
            if (LoweredUsername.contains("dog")||LoweredUsername.contains("yellow") || LoweredUsername.contains("four")){
                InappropriateUsernameErrorMessage.setVisible(true);
                check = true;
                break;
            }
            
            ArrayList<String> ExistingUsernames = Other.SQLStatements.GetExistingUsernames();

            for (int i = 0; i < ExistingUsernames.size(); i++) {
                if (ExistingUsernames.get(i).equals(NewUsername)) {
                    UniqueUsernameErrorMessage.setVisible(true);
                    check = true;
                    break;
                }
            }
            
            ExistingUsernames.clear();
            
             if (UniqueUsernameErrorMessage.isVisible()== true) {
                break;
            }
             
             break;
        }
        
        if (check == false){
            //ADD UPDATE BIT HERE
        }


    }//GEN-LAST:event_UsernameConfirmButtonActionPerformed

    private void UsernameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameButtonActionPerformed
        UsernameSection.setVisible(true);
        UsernameField.setVisible(true);
        UsernameConfirmButton.setVisible(true);
 
        UniqueUsernameErrorMessage.setVisible(false);
        LongUsernameErrorMessage.setVisible(false);
        InappropriateUsernameErrorMessage.setVisible(false);

        PasswordSection.setVisible(false);
        CurrentPasswordField.setVisible(false);
        NewPasswordField.setVisible(false);
        PasswordConfirmButton.setVisible(false);
        PasswordCharactersErrorMessage.setVisible(false);

        EmailSection.setVisible(false);
        EmailField.setVisible(false);
        EmailConfirmButton.setVisible(false);
        InvalidEmailErrorMessage.setVisible(false);
        UniqueEmailErrorMessage.setVisible(false);
    }//GEN-LAST:event_UsernameButtonActionPerformed

    private void PasswordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordButtonActionPerformed
        PasswordSection.setVisible(true);
        CurrentPasswordField.setVisible(true);
        NewPasswordField.setVisible(true);
        PasswordConfirmButton.setVisible(true);
        
        UsernameSection.setVisible(false);
        UsernameField.setVisible(false);
        UsernameConfirmButton.setVisible(false);
        UniqueUsernameErrorMessage.setVisible(false);
        LongUsernameErrorMessage.setVisible(false);
        InappropriateUsernameErrorMessage.setVisible(false);

        PasswordCharactersErrorMessage.setVisible(false);

        EmailSection.setVisible(false);
        EmailField.setVisible(false);
        EmailConfirmButton.setVisible(false);
        InvalidEmailErrorMessage.setVisible(false);
        UniqueEmailErrorMessage.setVisible(false);
    }//GEN-LAST:event_PasswordButtonActionPerformed

    private void PasswordConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordConfirmButtonActionPerformed
        PasswordCharactersErrorMessage.setVisible(false);
        
        String CurrentPassword = new String(CurrentPasswordField.getPassword());
        try{
        CurrentHashedPassword = Other.Utilities.GetHashedPassword(CurrentPassword);
        }catch (Exception e){
            System.out.println("Error with hashing password in account settings: "+e);
        }
        
        String NewPassword = new String(NewPasswordField.getPassword());
        boolean check = false;
        
        //NEW TO MAKE THEM PASSWORD FIELDS AND NOT TEXT FIELDS
        
        while (true){
            
            if (CurrentHashedPassword.equals(Other.NEAGame.CurrentUser.get(0).getPassword())){
                
            }
            
            
            if (NewPassword.length() < 8) {
                PasswordCharactersErrorMessage.setVisible(true);
                check = true;
                break;
            }
        }
        
        
        
    }//GEN-LAST:event_PasswordConfirmButtonActionPerformed

    private void EmailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailButtonActionPerformed
        EmailSection.setVisible(true);
        EmailField.setVisible(true);
        EmailConfirmButton.setVisible(true);
        
        UsernameSection.setVisible(false);
        UsernameField.setVisible(false);
        UsernameConfirmButton.setVisible(false);
        UniqueUsernameErrorMessage.setVisible(false);
        LongUsernameErrorMessage.setVisible(false);
        InappropriateUsernameErrorMessage.setVisible(false);

        PasswordSection.setVisible(false);
        CurrentPasswordField.setVisible(false);
        NewPasswordField.setVisible(false);
        PasswordConfirmButton.setVisible(false);
        PasswordCharactersErrorMessage.setVisible(false);

        InvalidEmailErrorMessage.setVisible(false);
        UniqueEmailErrorMessage.setVisible(false);
    }//GEN-LAST:event_EmailButtonActionPerformed

    private void EmailConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailConfirmButtonActionPerformed
        InvalidEmailErrorMessage.setVisible(false);
        UniqueEmailErrorMessage.setVisible(false);
        
        String NewEmail = EmailField.getText();
        boolean check = false;
        
        while(true){
            if (NewEmail.contains("@") && NewEmail.contains(".")) {

            } else {
                InvalidEmailErrorMessage.setVisible(true);
                check = true;
                break;
            }
            
            ArrayList<String> ExistingEmails = Other.SQLStatements.GetExistingEmails();
            
            for (int i = 0; i < ExistingEmails.size(); i++) {
                if (ExistingEmails.get(i).equals(NewEmail)) {
                    UniqueEmailErrorMessage.setVisible(true);
                    check = true;
                    break;
                }
            }
            
            ExistingEmails.clear();
            
            if(UniqueEmailErrorMessage.isVisible() == true){
                break;
            }
            
            break;
        }
        
        if (check == false){
            //ADD UPDATE BIT HERE
        }
        
        
        
        
        
    }//GEN-LAST:event_EmailConfirmButtonActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void NewPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Background;
    private javax.swing.JPasswordField CurrentPasswordField;
    private javax.swing.JButton EmailButton;
    private javax.swing.JButton EmailConfirmButton;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailSection;
    private javax.swing.JLabel InappropriateUsernameErrorMessage;
    private javax.swing.JLabel InvalidEmailErrorMessage;
    private javax.swing.JLabel LongUsernameErrorMessage;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JButton PasswordButton;
    private javax.swing.JLabel PasswordCharactersErrorMessage;
    private javax.swing.JButton PasswordConfirmButton;
    private javax.swing.JLabel PasswordSection;
    private javax.swing.JLabel UniqueEmailErrorMessage;
    private javax.swing.JLabel UniqueUsernameErrorMessage;
    private javax.swing.JButton UsernameButton;
    private javax.swing.JButton UsernameConfirmButton;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel UsernameSection;
    // End of variables declaration//GEN-END:variables
}
