/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIs;

import java.awt.Toolkit;

/**
 *
 * @author daisy
 */
public class SelectACharacterScreen extends javax.swing.JFrame {

    Toolkit tk = Toolkit.getDefaultToolkit();
    
    public SelectACharacterScreen() {
        initComponents();
        
        FiveCharactersErrorMessage.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        CreateANewCharacterButton = new javax.swing.JButton();
        FiveCharactersErrorMessage = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(39, 45, 230, 100);

        CreateANewCharacterButton.setBorderPainted(false);
        CreateANewCharacterButton.setContentAreaFilled(false);
        CreateANewCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateANewCharacterButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CreateANewCharacterButton);
        CreateANewCharacterButton.setBounds(550, 950, 820, 110);

        FiveCharactersErrorMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Five Characters Error Message.jpg"))); // NOI18N
        getContentPane().add(FiveCharactersErrorMessage);
        FiveCharactersErrorMessage.setBounds(720, 410, 500, 310);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/Select a Character Screen.jpg"))); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1930, 1100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        
        GUIs.LoginScreen login = new GUIs.LoginScreen();

        int WidthSize = (int) tk.getScreenSize().getWidth();
        int HeightSize = (int) tk.getScreenSize().getHeight();

        //(width, height)
        login.setSize(WidthSize, HeightSize);
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BackButtonActionPerformed

    private void CreateANewCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateANewCharacterButtonActionPerformed
        
        int CurrentCharacters = Other.SQLStatements.CountingCharacters(Other.NEAGame.CurrentUser.get(0).getUsername());
        System.out.println(Other.NEAGame.CurrentUser.get(0).getUsername()); //for testing
        
        if(CurrentCharacters >= 5){
            FiveCharactersErrorMessage.setVisible(true);
            Other.Utilities.wait(4000);
        }else{
            GUIs.NicknameChoosingScreen nicknameChoosing = new GUIs.NicknameChoosingScreen();
            
            int WidthSize = (int) tk.getScreenSize().getWidth();
            int HeightSize = (int) tk.getScreenSize().getHeight();
            
            nicknameChoosing.setSize(WidthSize, HeightSize);
            nicknameChoosing.setVisible(true);
            this.dispose();
        }
        
        
        
    }//GEN-LAST:event_CreateANewCharacterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectACharacterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectACharacterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectACharacterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectACharacterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectACharacterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel Background;
    private javax.swing.JButton CreateANewCharacterButton;
    private javax.swing.JLabel FiveCharactersErrorMessage;
    // End of variables declaration//GEN-END:variables
}
